export type Planet = {
  name: string
  color: [number, number, number]  // RGB
  r: number       // orb visual radius px
  orbit: number   // orbital semi-major axis (scaled later)
  tilt: number    // degrees
  period: number  // seconds per revolution
  angle0: number  // initial angle
  hasRing?: boolean
}

export const planets: Planet[] = [
  { name: 'Mercury', color: [180, 170, 155], r: 40,  orbit: 100,  tilt: 7,    period: 12, angle0: 0.4 },
  { name: 'Venus',   color: [196, 163, 90],  r: 55,  orbit: 160,  tilt: 3.4,  period: 18, angle0: 1.8 },
  { name: 'Earth',   color: [80, 140, 220],  r: 60,  orbit: 230,  tilt: 0,    period: 24, angle0: 3.5 },
  { name: 'Mars',    color: [200, 100, 70],  r: 45,  orbit: 300,  tilt: 1.85, period: 32, angle0: 5.1 },
  { name: 'Jupiter', color: [190, 155, 100], r: 100, orbit: 420,  tilt: 1.3,  period: 48, angle0: 0.8 },
  { name: 'Saturn',  color: [200, 180, 120], r: 85,  orbit: 540,  tilt: 2.49, period: 64, angle0: 2.4, hasRing: true },
  { name: 'Uranus',  color: [100, 180, 180], r: 65,  orbit: 660,  tilt: 0.77, period: 84, angle0: 4.2 },
  { name: 'Neptune', color: [70, 100, 200],  r: 60,  orbit: 780,  tilt: 1.77, period: 100, angle0: 5.8 },
]

// The article — one long continuous text about the solar system
export const HEADLINE = 'A JOURNEY THROUGH\nTHE SOLAR SYSTEM'

export const ARTICLE = `The Sun sits at the centre of our solar system, a middle-aged yellow dwarf star that contains 99.86 percent of all the mass in its gravitational domain. Eight planets orbit it, each a world unto itself, separated by vast emptiness that the human mind struggles to comprehend. Light from the Sun takes eight minutes to reach Earth, yet more than four hours to touch Neptune's atmosphere. Between those two facts lies the entire drama of planetary science.

Mercury, the innermost planet, races around the Sun every eighty-eight days. It has no atmosphere to speak of — just a battered surface of craters and scarps, baking at four hundred and thirty degrees on its sunlit face while plunging to minus one hundred and eighty on the far side. The Caloris Basin, fifteen hundred kilometres wide, records an ancient impact so violent it sent shockwaves through the entire planet. MESSENGER mapped its surface from orbit, discovering water ice hiding in permanently shadowed polar craters — a paradox on the planet closest to the Sun.

Venus comes next, shrouded in clouds of sulfuric acid. Beneath that veil the surface temperature reaches four hundred and sixty-five degrees Celsius, hotter than Mercury despite being farther from the Sun. A runaway greenhouse effect traps heat so effectively that the Soviet Venera landers survived only minutes on its surface. Venus rotates backwards, so slowly that its day outlasts its year. Recent phosphine detections in the upper atmosphere sparked fierce debate about whether microbial life could float in the cooler cloud layers fifty kilometres above the inferno.

Earth is the third rock from the Sun, and the only place we know harbours life. Seventy-one percent of its surface is covered by liquid water, held in place by an atmosphere that is seventy-eight percent nitrogen and twenty-one percent oxygen. A powerful magnetic field generated by the liquid iron outer core deflects the solar wind. The Moon, formed from a giant impact four and a half billion years ago, stabilises Earth's axial tilt at twenty-three and a half degrees, giving us the seasons that regulate the biosphere.

Mars, the Red Planet, wears a thin veil of carbon dioxide atmosphere at barely one percent of Earth's surface pressure. Olympus Mons rises twenty-two kilometres above the surrounding plains, the tallest volcano in the solar system. Valles Marineris stretches four thousand kilometres, a canyon so vast it would span the continental United States. Ancient river channels and mineral deposits prove that liquid water once flowed abundantly. Today five rovers have traversed its rust-coloured deserts, and Perseverance is caching rock samples for eventual return to Earth.

Beyond Mars lies the asteroid belt, and then Jupiter — king of the planets. Its mass exceeds all other planets combined by a factor of two and a half. The Great Red Spot, a storm larger than Earth, has persisted for at least three and a half centuries. Deep inside, hydrogen is compressed into a metallic liquid that generates the most powerful magnetic field of any planet. Ninety-five known moons orbit Jupiter, including Europa, whose subsurface ocean of liquid water is considered one of the most promising places to search for extraterrestrial life.

Saturn is the jewel of the solar system. Its ring system spans two hundred and eighty-two thousand kilometres but averages only ten metres in thickness — a structure of breathtaking delicacy. Composed of countless particles of ice and rock, the rings catch sunlight and scatter it into a display visible through even a modest telescope. Saturn's moon Titan possesses a dense atmosphere thicker than Earth's, with lakes of liquid methane on its surface. Enceladus erupts geysers of water ice from a subsurface ocean, making it another prime candidate for life beyond Earth.

Uranus rolls on its side, its axial tilt of ninety-eight degrees likely caused by a catastrophic collision in the early solar system. This ice giant appears blue-green because methane in its atmosphere absorbs red light. Twenty-seven moons orbit it, all named after characters from Shakespeare and Alexander Pope. Only Voyager 2 has visited, flying past in 1986 to reveal an atmosphere that appeared remarkably featureless — though recent observations show bright cloud formations and seasonal changes unfolding over its eighty-four-year orbit.

Neptune, the outermost planet, is a world of superlatives. Winds scream across its surface at two thousand one hundred kilometres per hour, the fastest in the solar system. It was the first planet discovered through mathematical prediction rather than direct observation. Its largest moon, Triton, orbits in a retrograde direction and erupts geysers of nitrogen gas — almost certainly a captured Kuiper Belt object. A full Neptunian year takes one hundred and sixty-five Earth years; it completed its first full orbit since discovery only in 2011.`
